#experiment parameters
ALGORITHM = "GA"
SALESMAN = 7  # NUMBER OF SALESMAN (2, 3, 5, 7)
CITIES = 51
FILE_PATH = "data//eil51.txt"

#GA PARAMETERS
GA_POPULATION_SIZE = 100
GA_MAX_ITERATIONS = 100
GA_MUTATION_PROBABILITY = 0.7
GA_CROSSOVER_PROBABILITY = 0.7